[default]
timeout = 120

[fashion]
title = "하퍼스바자 코리아 ─ 패션"
url = "https://www.harpersbazaar.co.kr/fashion"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"

[beauty]
title = "하퍼스바자 코리아 ─ 뷰티"
url = "https://www.harpersbazaar.co.kr/beauty"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"

[celebrity]
title = "하퍼스바자 코리아 ─ 셀레브리티"
url = "https://www.harpersbazaar.co.kr/celebrity"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"

[artandculture]
title = "하퍼스바자 코리아 ─ 아트&컬쳐"
url = "https://www.harpersbazaar.co.kr/artandculture"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"

[lifestyle]
title = "하퍼스바자 코리아 ─ 라이프스타일"
url = "https://www.harpersbazaar.co.kr/lifestyle"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"

[sustainability]
title = "하퍼스바자 코리아 ─ 지속가능성"
url = "https://www.harpersbazaar.co.kr/sustainability"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
