[naverpost_life]
title = "네이버 포스트 ─ 하퍼스바자 ─ Life"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=482346&memberNo=41829949"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_fashion]
title = "네이버 포스트 ─ 하퍼스바자 ─ Fashion"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=482340&memberNo=41829949"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_celebs]
title = "네이버 포스트 ─ 하퍼스바자 ─ Celebs"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=482345&memberNo=41829949"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_beauty]
title = "네이버 포스트 ─ 하퍼스바자 ─ Beauty"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=482343&memberNo=41829949"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_event]
title = "네이버 포스트 ─ 하퍼스바자 ─ EVENT"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=655219&memberNo=41829949"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_art]
title = "네이버 포스트 ─ 하퍼스바자 ─ Art"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=482347&memberNo=41829949"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[fashion]
title = "하퍼스바자 코리아 ─ 패션"
url = "https://www.harpersbazaar.co.kr/fashion"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 180

[beauty]
title = "하퍼스바자 코리아 ─ 뷰티"
url = "https://www.harpersbazaar.co.kr/beauty"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 180

[celebrity]
title = "하퍼스바자 코리아 ─ 셀레브리티"
url = "https://www.harpersbazaar.co.kr/celebrity"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 180

[artandculture]
title = "하퍼스바자 코리아 ─ 아트&컬쳐"
url = "https://www.harpersbazaar.co.kr/artandculture"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 180

[lifestyle]
title = "하퍼스바자 코리아 ─ 라이프스타일"
url = "https://www.harpersbazaar.co.kr/lifestyle"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 180

[sustainability]
title = "하퍼스바자 코리아 ─ 지속가능성"
url = "https://www.harpersbazaar.co.kr/sustainability"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 180
